services:
  dev:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/tuxon-os
    working_dir: /tuxon-os
    privileged: true
    restart: unless-stopped
    command: ["bash", "-c", "tail -f /dev/null"]
