services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/host-tuxon-os # read-only mount from host
    privileged: true
    command: >
      bash -c "
        rm -rf /opt/tuxon-os &&
        mkdir -p /opt/tuxon-os &&
        cp -r /host-tuxon-os/* /opt/tuxon-os/ &&
        cd /opt/tuxon-os &&
        ./build.sh --force-clean --release && cp /opt/tuxon-os/tuxonos.iso /host-tuxon-os/
      "
