#!/bin/sh

# Mount required filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Give system some time to settle
sleep 1

# Print some info
echo "Successfully mounted virtual filesystems"
exec /bin/sh